language: ruby
cache:
  directories:
    - bundle

rvm:
  - 2.0
  - 2.1.3
  - 2.3.1

bundler_args: "--without documentation --path bundle"

before_install:
  - gem install bundler

script:
  - bundle install
  - bundle exec rake spec
  - bundle exec danger --verbose
  - bundle exec danger init --mousey --impatient
